### ISSUE TITLE
Maven build fails with version 1.0

### ISSUE THREAD

**Issue by adamdec** [scalatest/scalatest-maven-plugin#23]
Configuration I am using:
```
<plugin>
<groupId>org.scalatest</groupId>
<artifactId>scalatest-maven-plugin</artifactId>
<version>${scalatest-maven-plugin.version}</version>
<configuration>
    <reportsDirectory>${project.build.directory}/surefire-reports</reportsDirectory>
    <junitxml>.</junitxml>
    <filereports>WDF TestSuite.txt</filereports>
</configuration>
<executions>
    <execution>
        <id>test</id>
        <goals>
            <goal>test</goal>
        </goals>
        <configuration>
            <suffixes>(?&lt;!Integration)(Test|Spec)</suffixes>
        </configuration>
    </execution>
    <execution>
        <id>integration-test</id>
        <phase>integration-test</phase>
        <goals>
            <goal>test</goal>
        </goals>
        <configuration>
            <suffixes>(?&lt;=Integration)(Test|Spec)</suffixes>
        </configuration>
    </execution>
</executions>
</plugin>
```

Error:
```
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ commons ---
The system cannot find the file specified.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.512 s
[INFO] Finished at: 2016-09-30T15:11:56+02:00
[INFO] Final Memory: 35M/441M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project commons: There are test failures -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project commons: There are test failures
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures
	at org.scalatest.tools.maven.TestMojo.execute(TestMojo.java:107)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 26 more 
```

**Comment by adamdec** [comment]
Created PR: https://github.com/scalatest/scalatest-maven-plugin/pull/24

**Comment by apodalyuk** [comment]
This is still an issue on 2.2.0. The exact cause of the problem is as follows:

- `<suffixes>` contain a regexp that includes `<` (or `&lt;`) symbol; for example, `(?&lt;!Integration)` to match non-integration tests
- when executing, maven forks scalatest using `cmd.exe /X /C "java org.scalatest.tools.Runner ... -q (?<!Integration) ..."`
- this causes cmd to break with "The system cannot find the file specified.", because it interprets the `<` symbol as a redirection command.
- escaping `<` as `^<` seems to help, but that's not a cross-platform compatible solution

Unfortunately, I wasn't able to find a proper workaround yet.

**Comment by cheeseng** [comment]
@apodalyuk I think we may do the escaping like we did in runpath: 

https://github.com/scalatest/scalatest-maven-plugin/blob/master/src/main/java/org/scalatest/tools/maven/AbstractScalaTestMojo.java#L487

We can escape that perhaps only for windows, do you think that will help?
