### ISSUE TITLE
Dependency missing for `com/vladsch/flexmark/util/ast/Node`

### ISSUE THREAD

**Issue by tribbloid** [scalatest/scalatest-maven-plugin#88]
When using the latest plugin `2.0.2` with scalatest 3.2.11 and the following configuration:

```
      <plugin>
        <groupId>org.scalatest</groupId>
        <artifactId>scalatest-maven-plugin</artifactId>
        <version>2.0.2</version>
        <configuration>
          <reportsDirectory>${project.build.directory}/test-results/scalatest</reportsDirectory>
          <junitxml>.</junitxml>
          <htmlreporters>${project.build.directory}/site/scalatest</htmlreporters>

        </configuration>
        <executions>
          <execution>
            <id>test</id>
            <goals>
              <goal>test</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

a Jar hell exception with the following stacktrace was thown:

```
java.lang.NoClassDefFoundError: com/vladsch/flexmark/util/ast/Node
07:08
	at org.scalatest.tools.ReporterFactory.createHtmlReporter(ReporterFactory.scala:194)
07:08
	at org.scalatest.tools.ReporterFactory.getReporterFromConfiguration(ReporterFactory.scala:245)
07:08
	at org.scalatest.tools.ReporterFactory$$anonfun$createReportersFromConfigurations$1.apply(ReporterFactory.scala:254)
07:08
	at org.scalatest.tools.ReporterFactory$$anonfun$createReportersFromConfigurations$1.apply(ReporterFactory.scala:253)
07:08
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
07:08
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
07:08
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
07:08
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
07:08
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
07:08
	at org.scalatest.tools.ReporterConfigurations.foreach(ReporterConfiguration.scala:42)
07:08
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
07:08
	at org.scalatest.tools.ReporterConfigurations.map(ReporterConfiguration.scala:42)
07:08
	at org.scalatest.tools.ReporterFactory.createReportersFromConfigurations(ReporterFactory.scala:253)
07:08
	at org.scalatest.tools.ReporterFactory.getDispatchReporter(ReporterFactory.scala:257)
07:08
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1480)
07:08
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
07:08
	at org.scalatest.tools.Runner$.main(Runner.scala:775)
07:08
	at org.scalatest.tools.Runner.main(Runner.scala)
07:08
Caused by: java.lang.ClassNotFoundException: com.vladsch.flexmark.util.ast.Node
07:08
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
07:08
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
07:08
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
07:08
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
07:08
	... 18 more
```

**Comment by clayreimann** [comment]
Have you added `flexmark-all` to your `dependencies` section?

```xml
    <dependencies>
        <dependency>
            <groupId>com.vladsch.flexmark</groupId>
            <artifactId>flexmark-all</artifactId>
            <version>0.62.2</version>
            <scope>test</scope>
        </dependency>
    <dependencies>
```

**Comment by cheeseng** [comment]
@bvenners @tribbloid @clayreimann I think this should be fixed by adding the flexmark dependency as suggested by @clayreimann , I think this can be closed.
